### ISSUE TITLE
cairowin32.nim(20 , 52) Error: undeclared identifier: 'pLOGFONTW'

### ISSUE THREAD

**Issue by encorehu** [nim-lang/cairo#5]
Hint: cairowin32 [Processing]
c:\documents and settings\administrator.nimble\pkgs\cairo-1.0\cairowin32.nim(20
, 52) Error: undeclared identifier: 'pLOGFONTW'

should change pLOGFONTW to PLOGFONTW, and fixed!

**Comment by enthus1ast** [comment]
still broken

**Comment by dom96** [comment]
PR please? :)
