### ISSUE TITLE
Windows dependency is broken

### ISSUE THREAD

**Issue by skyfex** [nim-lang/cairo#6]
Currently cairowin32 does not compile because it can't find the 'windows' module.

I'm not sure what the plan is with the windows API wrapper, but I suppose a quick fix is to add a dependency on the 'oldwinapi' package.

(I'm not sure how advanced the nimble dependency system is, but it would be nice if the dependency was only valid when using nimble on windows)

**Comment by treeform** [comment]
I have a fix for this in this PR: https://github.com/nim-lang/cairo/pull/11
